/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdoptImport } from './routes/adopt'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AdoptRoute = AdoptImport.update({
  id: '/adopt',
  path: '/adopt',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/adopt': {
      id: '/adopt'
      path: '/adopt'
      fullPath: '/adopt'
      preLoaderRoute: typeof AdoptImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/adopt': typeof AdoptRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adopt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adopt'
  id: '__root__' | '/' | '/adopt'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdoptRoute: typeof AdoptRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdoptRoute: AdoptRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/adopt"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/adopt": {
      "filePath": "adopt.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
